# Generated by Django 4.1.5 on 2023-01-14 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetQuery',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='QueryForUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('query_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_id_main', to='query.metquery')),
            ],
        ),
    ]
