# Generated by Django 4.1.5 on 2023-01-10 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metquery',
            name='location',
        ),
    ]
