# Generated by Django 4.1.5 on 2023-01-10 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='humidity',
            new_name='relative_humidity',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='actual_temperature',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='record',
            name='virtual_temperature',
        ),
    ]
