# Generated by Django 4.1.5 on 2023-01-10 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_rename_humidity_record_relative_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordforquery',
            name='record_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='record_id', to='records.record'),
        ),
    ]
