# Generated by Django 4.1.5 on 2023-01-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_recordforquery_record_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='virtual_temperature',
            field=models.DecimalField(decimal_places=4, default=99.99, max_digits=10),
            preserve_default=False,
        ),
    ]
